### ISSUE TITLE
Support for Pytorch 1.11?

### ISSUE THREAD

**Issue by bhosalems** [gdlg/pytorch_compact_bilinear_pooling#11]
Hi, 
torch.fft() and torch.irfft() are no more functions, those are modules. And there appears to be a lof of modification in the parameters. I am currently trying to combine the two types of features with compact bilinear pooling, do you know how to port this code to pytorch 1.11?

**Comment by MarihamR** [comment]
> Hi, torch.fft() and torch.irfft() are no more functions, those are modules. And there appears to be a lof of modification in the parameters. I am currently trying to combine the two types of features with compact bilinear pooling, do you know how to port this code to pytorch 1.11?

hello,
use torch.fft.rfft and torch.fft.irfft instead and i guess it should work
