### ISSUE TITLE
How does it work for a mini batch?

### ISSUE THREAD

**Issue by YanWang2014** [gdlg/pytorch_compact_bilinear_pooling#2]
Nice work. However, I do not understand how I can apply it with a mini batch of tensors

**Comment by gdlg** [comment]
Like so:
```
batch_size = 32
input_size = 2048
output_size = 16000

mcb = CompactBilinearPooling(input_size, input_size, output_size).cuda()

x = torch.autograd.Variable(torch.rand(batch_size,input_size).cuda())
y = torch.autograd.Variable(torch.rand(batch_size, input_size).cuda())

z = mcb(x,y)
```
This will produce a tensor z of size (32, 16000). 

The pooling is performed on the last dimension therefore you can also work with spatial data such as:

```
batch_size = 32
height = 14
width = 14

input_size = 2048
output_size = 16000

mcb = CompactBilinearPooling(input_size, input_size, output_size).cuda()

x = torch.autograd.Variable(torch.rand(batch_size, height, width, input_size).cuda())
y = torch.autograd.Variable(torch.rand(batch_size, height, width, input_size).cuda())

z = mcb(x,y)
```
which produces a tensor of size (32, 14, 14, 16000).

You can also backpropagate though the Python implementation is not as efficient memory-wise and performance-wise as the original implementation in Caffe.

**Comment by YanWang2014** [comment]
Thank you very much! By the way, why there is a `backward` method in `class CompactBilinearPoolingFn`? I mean, can't  PyTorch  do the back propagation automatically?

**Comment by gdlg** [comment]
Yes, in my first attempt, I was letting PyTorch do the backpropagation automatically however I found that it uses a fair amount of memory to store the tensors for most intermediate operations.
In this version, I only save the input tensors to have a smaller memory footprint at the expense of performances.

Ideally we need to write both forward and backward phases in CUDA.

**Comment by YanWang2014** [comment]
Thank you again. This helps me a lot.
