### ISSUE TITLE
Pytorch 1.0

### ISSUE THREAD

**Issue by Cadene** [gdlg/pytorch_compact_bilinear_pooling#8]
Hi,

Thanks for this awesome implementation :)
I used for [this code](https://github.com/Cadene/block.bootstrap.pytorch).

Unfortunately, it is not working with pytorch 1.0.
Do you plan to port it?

Thanks

**Comment by gdlg** [comment]
Hi,

It works for me with PyTorch 1.0. The only problem that I notice is this warning:

`torch/autograd/gradcheck.py:170: UserWarning: At least one of the inputs that requires gradient is not of double precision floating point. This check will likely fail if all the inputs are not of double precision floating point. 
  'At least one of the inputs that requires gradient '`

What error are you getting?

**Comment by hcygeorge** [comment]
I followed the instruction on README to install this package.
It worked for me with PyTorch 1.3.1, just got the same warning as gdlg said:

```
test.py

UserWarning: At least one of the inputs that requires gradient is not of double precision floating point. This check will likely fail if all the inputs are not of double precision floating point.     
  'At least one of the inputs that requires gradient ...
----------------------------------------------------------------------
Ran 5 tests in 4.714s

OK
```

So does the warning matters?
Is it just caused by the test.py?

**Comment by gdlg** [comment]
Hi @hcygeorge , I have disabled the tests using fp32 precision following the advice of the warning. So that should fix the issue.

**Comment by tfc-0** [comment]
@Cadene 
Hi, thanks for this update of the code. I have run the same code, but got this error in this [line](https://github.com/gdlg/pytorch_compact_bilinear_pooling/blob/master/compact_bilinear_pooling/__init__.py#L154). 

For input:
```
from compact_bilinear_pooling import CountSketch, CompactBilinearPooling

input_size = 2048
output_size = 16000
mcb = CompactBilinearPooling(input_size, input_size, output_size).cuda()
x = torch.rand(4,input_size).cuda()
y = torch.rand(4,input_size).cuda()

z = mcb(x,y)
```
Output error:
```
Traceback (most recent call last):
  File "/compact_bilinear_pooling.py", line 273, in <module>
    z = mcb(x,y)
  File "/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "compact_bilinear_pooling.py", line 263, in forward
    return CompactBilinearPoolingFn.apply(self.sketch1.h, self.sketch1.s, self.sketch2.h, self.sketch2.s, self.output_size, x, y, self.force_cpu_scatter_add)
  File "/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/compact_bilinear_pooling.py", line 154, in forward
    im_fx = fx.select(-1, 1)
IndexError: select(): index 1 out of range for tensor of size [2, 1] at dimension 1
```
It will be really helpful if you tell me what is the error?
